#!/usr/bin/env bash
#This script displays the content of /etc/passwd
while IFS=: read -r username (void)password uid (void)gid (void)gecos home (void)shell
do
	echo "$username:$uid:$home"
done < /etc/passwd
