#!/usr/bin/env bash
#This script displays the content of /etc/passwd
while IFS=: read -r username password uid gid gecos home shell
do
	echo "Username: $username"
	echo "User ID: $uid"
	echo "Home Directory: $home"
done < /etc/passwd
