#!/usr/bin/env bash
##This script displays content in /etc/passwd in a specific format##

##splits lines into fields for clean formatting
IFS=:


##reads /passwd line by line
while read -r username password uid gid groups home shell; do
	output="The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $uid"
	echo "$output"
done < /etc/passwd
