#!/usr/bin/env bash
##This script displays content in /etc/passwd in a specific format##

#current uid
current_uid=$(id -u)

#this splits all the lines into fields properly with IFS
IFS=:

while read -r username password uid gid groups home shell; do
	position=$((uid - current_uid))
	output="The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $username"
	echo "$output"
done < /etc/passwd
