#!/usr/bin/env bash
#This script displays Best School 10 times, but displays hi on a new line on the 9th iteration
counter=0
while [[ $coutner -lt 10 ]];do
	if [[ $counter -eq 9 ]];then
	echo "Hi"
	else
	echo "Best School"
	fi
	((counter++))
done
