#!/usr/bin/env bash
##This script displays numbers 1-20, and displays "bad luck from china" on the 4th loop, "bad luck from japan" on the 9th, and "bad luck from italy" on the 17th##
counter=1
while [ $counter -le 20 ]; do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from China"
			;;
		9)
			echo "$counter"
			echo "bad luck from Japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from Italy"
			;;
		*)
			echo "$counter"
			;;
		esac
		((counter++))
done
