#!/usr/bin/env bash
##This script displays numbers 1-20, and displays "bad luck from china" on the 4th loop, "bad luck from japan" on the 9th, and "bad luck from italy" on the 17th##
counter=1
while [ $counter -le 20 ]; do
	if [ $counter -eq 4 ]; then
	echo "bad luck from China"
	elif [ $counter -eq 9 ]; then
	echo "bad luck from Japan"
	if [$ $counter -eq 17 ]; then
	echo "bad luck from Italy"
	fi
((counter++))
done
