#!/usr/bin/env bash
##this script displays the time for 12 hours and 59 minutes##
Hour=0
minute=1

while [ $Hour -le 12 ] && [ $minute -le 59 ]; do
		echo "$minute"
	if [ $minute -eq 59 ]; then
		echo ": $Hour"
		minute=1
		((Hour++))
	fi
	((minute++))
done
