#!/usr/bin/env bash
##this script displays the time for 12 hours and 59 minutes##
hour=0
minute=1

while [ $hour -le 12 ] && [ $minute -le 59]; do
	echo "$hour:$minute"
	((minute++))

	if [ $minute -gt 59 ]; then
	minute=1
	((hour++))
fi
done
