#!/usr/bin/env bash
##this script displays the time for 12 hours and 59 minutes##
hour=0
minute=1

while [ $hour -le 12 ] && [ $minute -le 59 ]; do
	if [ $hour -lt 10 ]; then
		echo -n "0$hour:"
	else
		echo -n "$hour:"
	fi
	if [ $minute -lt 10 ]; then
		echo -n "0$minute"
	else
		echo -n "$minute"
	fi
	((minute++))
	if [ $ minute -gt ]; then
		minute=1
		((hour++))
	fi
done
