#!/usr/bin/env bash
##This script displays a list of content in the current directory and removes any number or dash before the name
for file in *; do
	if [[ $file == -* ]]; then
		no_dash=${file#*-}
		echo "$no_dash"
	else
		echo "$file"
	fi
done
