#!/usr/bin/env bash
##This script displays a list of content in the current directory and removes any number or dash before the name
items=$(find. -maxdepth 1)
for item in $items; do
	after_dash=$(echo "$item" | grep -oE '[^-]*$')
	echo "$after_dash"
done
